---
- name: download tomcat tar file
  get_url: 
   url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.35/bin/apache-tomcat-9.0.35.tar.gz
   dest: /home/ubuntu/apache-tomcat-9.0.35.tar.gz
   force_basic_auth: yes

- name: create tomcat folder
  file: 
   path: /opt/tomcat
   state: directory

- name: extract tar file
  command:
    cmd: sudo tar xzvf /home/ubuntu/apache-tomcat-9.0.35.tar.gz -c /opt/tomcat
    creates: /opt/tomcat/license
  